/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

 
import java.util.ArrayList;
import java.util.Comparator;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Rafael Avila
 */
public class EjercicioStream extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    int aplicar = 0;
    ArrayList<Persona> Mordenacion = menuprincipal.listPersona;

    ArrayList<Persona> busqueda = menuprincipal.listPersona;

 
    public EjercicioStream() {
        initComponents();

        btnRefrescar.setEnabled(false);
        gestionarinformededatos(menuprincipal.listPersona);
        setLocationRelativeTo(null);
 

    }

    public void Buscarpersonas(String auxBuscar) {
        int opcion = jcmbopdat.getSelectedIndex();
       
        //Aqui provcedemos a utlizar el metodo filter se asigna mediante una funcion lambda
        //validara  cada uno de los datos escogidos por el usuario
        if (opcion == 0) {
            busqueda = (ArrayList<Persona>) menuprincipal.listPersona.stream()
                    .filter(persona -> persona.getNombre().equalsIgnoreCase(auxBuscar)).collect(Collectors.toList());
        }
        if (opcion == 1) {
            busqueda = (ArrayList<Persona>) menuprincipal.listPersona.stream()
                    .filter(persona -> persona.getApellido1().equalsIgnoreCase(auxBuscar)).collect(Collectors.toList());
        }
        if (opcion == 2) {
            busqueda = (ArrayList<Persona>) menuprincipal.listPersona.stream()
                    .filter(persona -> persona.getApellido2().equalsIgnoreCase(auxBuscar)).collect(Collectors.toList());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jcmbopdat = new javax.swing.JComboBox<>();
        txtdatosper = new javax.swing.JTextField();
        btnflitro = new javax.swing.JButton();
        lbMetodo = new javax.swing.JLabel();
        lbMetodo1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldatospersona = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbOrdenar = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        cbOrdenar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcmbopdat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcmbopdat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido Paterno", "apellido Materno" }));
        jcmbopdat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbopdatItemStateChanged(evt);
            }
        });

        txtdatosper.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnflitro.setBackground(new java.awt.Color(0, 204, 204));
        btnflitro.setText("FILTRAR");
        btnflitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnflitroActionPerformed(evt);
            }
        });

        lbMetodo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lbMetodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMetodo.setText("Ingresa el dato especifico de la persona:");

        lbMetodo1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lbMetodo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMetodo1.setText("Elige la opcion del dato con el que quieres filtar");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Nombre");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Apellido Paterno");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Apellido Materno");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnflitro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMetodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jcmbopdat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButton3)
                        .addGap(378, 378, 378))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(txtdatosper, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(253, 253, 253))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lbMetodo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jcmbopdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMetodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtdatosper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnflitro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 980, 230));

        tbldatospersona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbldatospersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbldatospersona);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 950, 260));

        btnRefrescar.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        btnRefrescar.setText("Reiniciar Consulta");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 30));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setText(" stream persona");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lbOrdenar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbOrdenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOrdenar.setText("Ordenar");
        getContentPane().add(lbOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, -1));

        jButton6.setText("Ascendente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, -1, -1));

        jButton7.setText("Descendente");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 590, -1, -1));

        cbOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ascendente", "descendente" }));
        cbOrdenar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbOrdenarItemStateChanged(evt);
            }
        });
        getContentPane().add(cbOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-photo-minimalistic-dark-blue-polygonal-background.jpeg"))); // NOI18N
        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbopdatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbopdatItemStateChanged
        String opcion = jcmbopdat.getSelectedItem().toString();
//        String opcion2 = jRadioButton2.getSelectedIcon().toString();
        lbMetodo.setText(opcion);

    }//GEN-LAST:event_jcmbopdatItemStateChanged

    private void btnflitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnflitroActionPerformed
        Buscarpersonas(txtdatosper.getText());
        gestionarinformededatos(busqueda);
        txtdatosper.setText("");
//        cmborden.setEnabled(false);
        btnRefrescar.setEnabled(true);
    }//GEN-LAST:event_btnflitroActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed
        gestionarinformededatos(menuprincipal.listPersona);
        btnRefrescar.setEnabled(true);
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//        Lista1 = (ArrayList<Persona>) Lista1.stream()
//        .sorted(Comparator.comparing(Persona::getApellido)).collect(Collectors.toList());
//        Listar(Lista1);
//        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        menuprincipal.listPersona = (ArrayList<Persona>) menuprincipal.listPersona.stream()
         .sorted(Comparator.comparing(Persona::getApellido1)).collect(Collectors.toList());
//        Listar(Lista1);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        //        String opcion2 = jRadioButton2.getText().toString();
        //        lbMetodo.setText(opcion2);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        // TODO add your handling code here:
        //          String opcion4 = buttonGroup1.getSelection().toString();
        //        String opcion2 = jRadioButton2.getText().toString();
        //        lbMetodo.setText(opcion2);
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        //        String opcion1 = jRadioButton1.getText().toString();
        //        lbMetodo.setText(opcion1);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        // TODO add your handling code here:
        //        String opcion2 = buttonGroup1.getClass().toString();
        //        lbMetodo.setText(opcion2);
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void cbOrdenarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbOrdenarItemStateChanged
     
    }//GEN-LAST:event_cbOrdenarItemStateChanged

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EjercicioStream().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnflitro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbOrdenar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcmbopdat;
    private javax.swing.JLabel lbMetodo;
    private javax.swing.JLabel lbMetodo1;
    private javax.swing.JLabel lbOrdenar;
    private javax.swing.JTable tbldatospersona;
    private javax.swing.JTextField txtdatosper;
    // End of variables declaration//GEN-END:variables

 
    public void gestionarinformededatos(ArrayList<Persona> auxi) {

        String[] cabezeras
                = {
                    "Nombre",
                    "Apellido 1",
                    "Apellido 2"
                };

        model.setColumnIdentifiers(cabezeras);
        model.setRowCount(0);

        auxi.stream().map(historial -> {
            Object[] datos = new Object[3];
            datos[0] = historial.getNombre();
            datos[1] = historial.getApellido1();
            datos[2] = historial.getApellido2();
            return datos;
        }).forEach(model::addRow);
        tbldatospersona.setModel(model);

    }

}
